### ISSUE TITLE
HALCodec no format

### ISSUE THREAD

**Issue by marcoooo** [core-api/python-hal-codec#12]
I am unable to uses coreapi client get function with a forced format because HALCodec doesn't define 'format' attribute such as basic coreapi ones (v2.3.3)

``` python

class JSONCodec(BaseCodec):
    media_type = 'application/json'
    format = 'json'
```

**Comment by lovelydinosaur** [comment]
I'm no longer supporting this repo. I guess subclass the codec.

**Comment by marcoooo** [comment]
Thank you for the update. Should I get rid of the codec ? And use another one then ? (unfortunately, the HAL codec is in use for my API https://www.ebi.ac.uk/ols/api/ontologies. Is there another codec which works with this format ?
