### ISSUE TITLE
Document not kept pace with coreapi Document class

### ISSUE THREAD

**Issue by danballance** [core-api/python-hal-codec#8]
After updating my packages I've noticed that the way _parse_document instantiates the Document object to return is now out of date with the coreapi.document.Document class. I get this error:

```
  File "/home/dan/Code/python/public-api-client/env2/local/lib/python2.7/site-packages/hal_codec/__init__.py", line 190, in _parse_document
    return Document(url, title, content)
  File "/home/dan/Code/python/public-api-client/env2/local/lib/python2.7/site-packages/coreapi/document.py", line 60, in __init__
    raise TypeError("'description' must be a string.")
TypeError: 'description' must be a string.
```

It's because the third parameter to Document.__init__ is now description whereas it was previously content. I'm just putting a quick pull request together for this now.

**Comment by danballance** [comment]
Hi, sorry to be a pain, but can I bump this please? Can you confirm this issue or do I just need to move to different versions? I keep getting this error when I install from pip.

**Comment by lovelydinosaur** [comment]
Yup. Sure, I'll get onto it this week. 😀

**Comment by danballance** [comment]
That's great, thanks. I'm also happy to help if you are busy. I sent a simple PR there that solves the issue for me locally, but of course it may just be fixing the symptom rather than the underling cause and you obviously know your own framework :)

**Comment by nayanchandni** [comment]
Hi.
I am getting the same error when trying to do codec.load().
<img width="813" alt="screen shot 2017-03-02 at 1 24 35 pm" src="https://cloud.githubusercontent.com/assets/18507029/23521104/acb08a76-ff4b-11e6-8929-118a90eca9f4.png">

Can you comment if this has been solved?

**Comment by lovelydinosaur** [comment]
Now resolved in Version 1.0.2.
Thanks @danballance, @nayanchandni & apologies for the delay!

**Comment by nayanchandni** [comment]
Also,

I am not sure if HALCodec() works when a url returns an array/list of _links{} objects. Is this correct?

**Comment by danballance** [comment]
Perfect, I'll do some testing today!

**Comment by danballance** [comment]
This is working for me now, thanks very much for the update :)
